apiVersion: v1
kind: Namespace
metadata:
  name: katalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: katalog-collector
  namespace: katalog
  labels:
    app: katalog-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katalog-collector
  template:
    metadata:
      labels:
        app: katalog-collector
    spec:
      containers:
      - name: katalog-collector
        image: katalog
        env:
        - name: PUBLISHER
          value: "kafka"
        - name: KAFKA_URL
          value: "kafka.kafka:9092"
        resources:
            limits:
              memory: 200Mi
              cpu: "100m"
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - name: tmp
        emptyDir: {}