[[constraint]]
  name = "github.com/emirpasic/gods"
  version = "1.12.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.7.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.3"

[[constraint]]
  name = "github.com/verdverm/frisby"
  version = "1.0.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "10.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/maxcnunes/httpfake"
  version = "1.0.1"
