---
resources:
  - name: katalog-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/walmartdigital/katalog

  - name: golang-1.11.x-image
    type: registry-image
    icon: docker
    source:
      repository: golang
      tag: 1.11-stretch

jobs:
- name: build
  serial: true
  plan:
  - aggregate:
    - get: katalog-git
      trigger: true
    - get: golang-1.11.x-image
      trigger: true
  - task: unit-testing
    image: golang-1.11.x-image
    file: katalog-git/concourse/build.yaml